site_name: global-techdocs
site_description: Parasol Architecture
repo_url: https://{{ gitlab_host }}/global/global-techdocs
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Architecture Discussions:
      - Core Services Overview: parasol/parasol-store.md
      - Consumer Web Steps: parasol/parsol-web.md
